DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_asc_account;
CREATE TABLE /*TABLE_PREFIX*/t_asc_account (
pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
s_name VARCHAR(100),
s_url VARCHAR(500),
s_key VARCHAR(200),
s_columns VARCHAR(2000),
s_status VARCHAR(50),
s_message VARCHAR(5000),
i_synced_from BIGINT(40) DEFAULT 0,
i_synced_to BIGINT(40) DEFAULT 0,
i_last_user_id INT UNSIGNED,
dt_last_sync TIMESTAMP,

PRIMARY KEY (pk_i_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';



DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_asc_log;
CREATE TABLE /*TABLE_PREFIX*/t_asc_log (
pk_i_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
fk_i_account_id INT UNSIGNED NOT NULL,
s_type VARCHAR(10),
s_content VARCHAR(5000),
s_response VARCHAR(2000),
s_name VARCHAR(50),
s_key VARCHAR(200),
s_code VARCHAR(20),
s_ip VARCHAR(20),
dt_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

PRIMARY KEY (pk_i_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';