SET FOREIGN_KEY_CHECKS=0;


DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_itp_item;
CREATE TABLE /*TABLE_PREFIX*/t_itp_item (
  fk_i_item_id INT UNSIGNED NOT NULL,
  s_password VARCHAR(50),
  s_password_alt VARCHAR(50),
  s_secret VARCHAR(50),
  i_failed_count INT(3) DEFAULT 0,
  dt_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (fk_i_item_id),
  FOREIGN KEY (fk_i_item_id) REFERENCES /*TABLE_PREFIX*/t_item (pk_i_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';


SET FOREIGN_KEY_CHECKS=1;